# Radius Recipe: Azure Database for MySQL (AVM)
# Auto-generated by rad app generate
# Uses Azure Verified Module: avm/res/db-for-my-sql/flexible-server

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "context" {
  description = "Radius-provided context for the recipe"
  type        = any
}

locals {
  name           = var.context.resource.name
  tags           = try(var.context.resource.tags, {})
  resource_group = try(var.context.azure.resourceGroup.name, "radius-${var.context.environment.name}")
  location       = try(var.context.azure.location, "eastus")
  sku_name       = "B_Standard_B1s"
  mysql_version  = "8.0.21"
  database_name  = var.context.resource.name
}

resource "random_string" "suffix" {
  length  = 8
  special = false
  upper   = false
}

resource "random_password" "admin_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# Azure Database for MySQL Flexible Server using AVM module
module "mysql" {
  source  = "Azure/avm-res-dbformysql-flexibleserver/azurerm"
  version = "0.1.5"

  name                          = "${local.name}-${random_string.suffix.result}"
  resource_group_name           = local.resource_group
  location                      = local.location
  sku_name                      = local.sku_name
  mysql_flexible_server_version = local.mysql_version

  administrator_login    = "mysqladmin"
  administrator_password = random_password.admin_password.result

  databases = {
    (local.database_name) = {
      charset   = "utf8mb4"
      collation = "utf8mb4_unicode_ci"
    }
  }

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

output "result" {
  description = "Recipe output values for Radius"
  sensitive   = true
  value = {
    values = {
      host     = module.mysql.fqdn
      port     = 3306
      database = local.database_name
      username = "mysqladmin"
    }
    secrets = {
      password         = random_password.admin_password.result
      connectionString = "mysql://mysqladmin:${random_password.admin_password.result}@${module.mysql.fqdn}:3306/${local.database_name}"
    }
    resources = [
      module.mysql.resource_id
    ]
  }
}
