# Radius Recipe: Azure Cache for Redis
# Auto-generated by rad app generate
# Uses native azurerm resources for Azure Cache for Redis

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "context" {
  description = "Radius-provided context for the recipe"
  type        = any
}

locals {
  name              = var.context.resource.name
  tags              = try(var.context.resource.tags, {})
  resource_group    = try(var.context.azure.resourceGroup.name, "radius-${var.context.environment.name}")
  location          = try(var.context.azure.location, "eastus")
  sku_name          = "Basic"
  family            = "C"
  capacity          = 0
  enable_non_ssl    = true
}

resource "random_string" "suffix" {
  length  = 8
  special = false
  upper   = false
}

# Azure Cache for Redis using native azurerm resources
resource "azurerm_redis_cache" "redis" {
  name                = "${local.name}-${random_string.suffix.result}"
  location            = local.location
  resource_group_name = local.resource_group
  capacity            = local.capacity
  family              = local.family
  sku_name            = local.sku_name
  enable_non_ssl_port = local.enable_non_ssl

  redis_configuration {}

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

output "result" {
  description = "Recipe output values for Radius"
  sensitive   = true
  value = {
    values = {
      host       = azurerm_redis_cache.redis.hostname
      port       = local.enable_non_ssl ? azurerm_redis_cache.redis.port : azurerm_redis_cache.redis.ssl_port
      tls        = !local.enable_non_ssl
    }
    secrets = {
      password   = azurerm_redis_cache.redis.primary_access_key
      connection = azurerm_redis_cache.redis.primary_connection_string
    }
    resources = [
      azurerm_redis_cache.redis.id
    ]
  }
}
