# Radius Recipe: Azure Cache for Redis
# Copied from local repository: infra/main.tf
# This recipe wraps the Redis resource definitions from your existing terraform code.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0, < 4.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

# NOTE: provider "azurerm" block is generated by Radius with credentials

variable "context" {
  description = "Radius-provided context for the recipe"
  type        = any
}

locals {
  name           = var.context.resource.name
  tags           = try(var.context.resource.tags, {})
  resource_group = try(var.context.azure.resourceGroup.name, "radius-${var.context.environment.name}")
  location       = try(var.context.azure.location, "eastus")
}

resource "random_string" "suffix" {
  length  = 8
  special = false
  upper   = false
}

# Azure Cache for Redis
# Copied from local infra/main.tf - azurerm_redis_cache resource
resource "azurerm_redis_cache" "main" {
  name                = "${local.name}-${random_string.suffix.result}"
  location            = local.location
  resource_group_name = local.resource_group
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"

  tags = merge(local.tags, {
    "radapp-resource"    = var.context.resource.id
    "radapp-environment" = var.context.environment.id
  })
}

output "result" {
  description = "Recipe output values for Radius"
  sensitive   = true
  value = {
    values = {
      host = azurerm_redis_cache.main.hostname
      port = azurerm_redis_cache.main.port
      tls  = false
    }
    secrets = {
      password   = azurerm_redis_cache.main.primary_access_key
      connection = azurerm_redis_cache.main.primary_connection_string
    }
    resources = [
      azurerm_redis_cache.main.id
    ]
  }
}
