# Radius Recipe: Azure Load Balancer
# Auto-generated by rad app generate
# Creates Azure Load Balancer with public IP for ingress

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0, < 4.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "context" {
  description = "Radius-provided context for the recipe"
  type        = any
}

locals {
  name           = var.context.resource.name
  tags           = try(var.context.resource.tags, {})
  resource_group = try(var.context.azure.resourceGroup.name, "radius-${var.context.environment.name}")
  location       = try(var.context.azure.location, "eastus")
}

resource "random_string" "suffix" {
  length  = 8
  special = false
  upper   = false
}

# Public IP for Load Balancer
resource "azurerm_public_ip" "main" {
  name                = "${local.name}-pip-${random_string.suffix.result}"
  location            = local.location
  resource_group_name = local.resource_group
  allocation_method   = "Static"
  sku                 = "Standard"

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

# Azure Load Balancer
resource "azurerm_lb" "main" {
  name                = "${local.name}-lb-${random_string.suffix.result}"
  location            = local.location
  resource_group_name = local.resource_group
  sku                 = "Standard"

  frontend_ip_configuration {
    name                 = "frontend"
    public_ip_address_id = azurerm_public_ip.main.id
  }

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

output "result" {
  description = "Recipe output values for Radius"
  value = {
    values = {
      hostname  = azurerm_public_ip.main.ip_address
      publicIP  = azurerm_public_ip.main.ip_address
      port      = 80
      lbId      = azurerm_lb.main.id
    }
    resources = [
      azurerm_lb.main.id,
      azurerm_public_ip.main.id
    ]
  }
}
