# Radius Recipe: Azure Load Balancer (AVM)
# Auto-generated by rad app generate
# Uses Azure Verified Module: avm/res/network/load-balancer

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "context" {
  description = "Radius-provided context for the recipe"
  type        = any
}

locals {
  name           = var.context.resource.name
  tags           = try(var.context.resource.tags, {})
  resource_group = try(var.context.azure.resourceGroup.name, "radius-${var.context.environment.name}")
  location       = try(var.context.azure.location, "eastus")
  sku            = "Standard"
}

resource "random_string" "suffix" {
  length  = 8
  special = false
  upper   = false
}

# Create a public IP for the load balancer
module "public_ip" {
  source  = "Azure/avm-res-network-publicipaddress/azurerm"
  version = "~> 0.1"

  name                = "${local.name}-pip-${random_string.suffix.result}"
  resource_group_name = local.resource_group
  location            = local.location
  allocation_method   = "Static"
  sku                 = local.sku

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

# Azure Load Balancer using AVM module
module "load_balancer" {
  source  = "Azure/avm-res-network-loadbalancer/azurerm"
  version = "~> 0.2"

  name                = "${local.name}-lb-${random_string.suffix.result}"
  resource_group_name = local.resource_group
  location            = local.location
  sku                 = local.sku

  frontend_ip_configurations = {
    frontend = {
      name                 = "frontend"
      public_ip_address_id = module.public_ip.resource_id
    }
  }

  tags = merge(local.tags, {
    "radapp.io/resource"    = var.context.resource.id
    "radapp.io/environment" = var.context.environment.id
  })
}

output "result" {
  description = "Recipe output values for Radius"
  value = {
    values = {
      hostname  = module.public_ip.ip_address
      publicIP  = module.public_ip.ip_address
      port      = 80
      lbId      = module.load_balancer.resource_id
    }
    resources = [
      module.public_ip.resource_id,
      module.load_balancer.resource_id
    ]
  }
}
